[wip] feat: input component page
diete-design/diete.design pull request #149
Opened 2024-05-19 19:03 UTC by hlavkat

2024-05-21 13:12 UTC, vojtechsimetka requested changes

2024-05-21 13:12 UTC, vojtechsimetka commented on src/routes/components/input/+page.svelte
> +{#snippet examples()}{/snippet}
Please add some examples.

2024-05-21 13:12 UTC, vojtechsimetka commented on src/routes/components/input/+page.svelte
> +{/snippet}
Remove lorem ipsum

2024-05-21 13:12 UTC, vojtechsimetka commented on src/routes/components/input/+page.svelte
> +	tagline="Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, quae?"
```suggestion
	tagline="
Input elements allow people to enter and edit text or data within a form."
```

2024-05-22 09:09 UTC, vojtechsimetka approved these changes

2024-05-22 09:34 UTC, agazso commented on src/routes/components/input/+page.svelte
> +		<Checkbox bind:checked={colorButton} label="Color palete button" />
```suggestion
		<Checkbox bind:checked={colorButton} label="Color palette button" />
```

2024-05-22 09:35 UTC, agazso commented on src/routes/components/input/+page.svelte
> +	/* .example-row {
Please remove commented code.

2024-05-22 09:35 UTC, agazso commented on src/routes/components/input/+page.svelte
> +	} */
```suggestion
```

2024-05-22 09:37 UTC, agazso approved these changes
Mostly good, see my comments.

I think we should also add the Button component source code to the implementation, because the Input depends on that.

2024-05-22 15:25 UTC, merged