[wip] feat: select component page
diete-design/diete.design pull request #154
Opened 2024-05-20 09:59 UTC by hlavkat

2024-05-21 13:54 UTC, vojtechsimetka requested changes

2024-05-21 13:54 UTC, vojtechsimetka commented on src/routes/components/select/+page.svelte
> +{/snippet}
Please add two options for each select and a placeholder.

2024-05-21 13:54 UTC, vojtechsimetka commented on src/routes/components/select/+page.svelte
> +		</TabContent>
Add placeholder and helpertext

2024-05-21 13:54 UTC, vojtechsimetka commented on src/routes/components/select/+page.svelte
> +{/snippet}
Add configuration for helper text and placeholder

2024-05-21 13:56 UTC, vojtechsimetka commented on src/routes/components/select/+page.svelte
> +	tagline="Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae, eveniet."
```suggestion
	tagline="Select components allow people to choose one option from a dropdown list"
```

2024-05-22 15:59 UTC, agazso approved these changes

2024-05-23 07:38 UTC, merged