[wip] feat: menu component
diete-design/diete.design pull request #47
Opened 2024-04-19 13:40 UTC by hlavkat

2024-04-25 09:00 UTC, vojtechsimetka requested changes

2024-04-25 09:00 UTC, vojtechsimetka commented on src/lib/components/ui/menu/menu-item.svelte
> +</a>
This should be both `button` and `a` element. Ideally, here we should just use `Button` component we already have

2024-04-25 09:00 UTC, vojtechsimetka commented on src/routes/+page.svelte
> +			</MenuTitle>
Please add disabled variant

2024-04-26 15:52 UTC, vojtechsimetka approved these changes
LGTM, ready for final review @agazso

2024-04-26 17:49 UTC, agazso approved these changes
Nice!

2024-04-26 17:49 UTC, agazso commented on src/routes/+page.svelte
> +	<div class="row">
Missing section id and title:

```suggestion
<section id="menu">
        <Typography variant="h1">Menu</Typography>
	<div class="row">
```

2024-04-27 09:28 UTC, merged