fix: opening and closeing the menu by clicking the caret
diete-design/diete.design pull request #63
Opened 2024-04-24 08:16 UTC by hlavkat

resolve #61

2024-04-24 12:03 UTC, vojtechsimetka requested changes
Thanks, this works but I have few comments:

- It probably should be `button` instead of `div` (for accessibility reasons)
- if it is a `button` then `onkeypress` will work correctly out of the box, otherwise it should have the same code as the `onclick` handler but with `enter` key

2024-04-25 13:16 UTC, vojtechsimetka approved these changes
Mostly good from my end, WDYT @agazso ?

2024-04-25 13:16 UTC, vojtechsimetka commented on src/lib/components/ui/select/select.svelte
> +		})
do we need this on `window` or can we have it just on the `input` element?

2024-04-25 13:49 UTC, agazso approved these changes
So now it closes the menu, so functionally it works.

It still leaves the input active (focused) which is debatable, but at least it is consistent with what happens when you click the input twice (once to open and again to close). 

However there is a slight difference, when the caret is clicked there is an intermediate unfocused state with a small animation and the background turning grey. With clicking the input twice there is no intermediate state, and that makes clicking the caret feeling "glitchy".  This also happens when the input is focused and the caret is clicked to open it.

This seems like a minor detail, but these small inconsistencies makes the difference for people to feel the experience as smooth vs. buggy. Feel free to address this in another issue/PR.

2024-05-06 16:02 UTC, merged